# syntax=docker/dockerfile:1
FROM node:18-buster-slim
LABEL Name=nc-frontend-prod Version=0.1.0

WORKDIR /frontend
COPY package.json /frontend/

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN npm install --loglevel verbose

COPY . /frontend/

RUN npm run build

EXPOSE 3000

RUN ["chmod", "+x", "/frontend/entrypoint.prod.sh"]
ENTRYPOINT ["/frontend/entrypoint.prod.sh"]
