# Generated by Django 4.1.7 on 2023-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
