# Generated by Django 4.1.7 on 2023-03-25 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_organization_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="author",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="slug",
        ),
    ]
