# Generated by Django 4.1.7 on 2023-03-25 21:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_article_slug_author_slug_category_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capsule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("points", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=["title"], unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capsules",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capsule",
                "verbose_name_plural": "Capsules",
                "ordering": ("-id",),
            },
        ),
    ]
