# Generated by Django 4.1.7 on 2023-03-26 20:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_article_is_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["organization__name", "title"],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["title"],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
    ]
