# Generated by Django 4.1.7 on 2023-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_alter_article_slug_alter_author_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capsule",
            name="sentiment",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
