# Generated by Django 4.1.7 on 2023-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_institution_location_person_tag_capsule_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
