# Generated by Django 4.1.7 on 2023-03-29 17:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0012_alter_capsule_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                populate_from=["name"],
                unique=True,
            ),
        ),
    ]
