# Generated by Django 4.1.7 on 2023-04-01 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0013_institution_slug_location_slug_person_slug_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="capsule",
            name="status",
            field=models.CharField(
                choices=[("N", "Normal"), ("F", "Featured"), ("B", "Breaking")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="status_duration",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(48),
                ],
            ),
        ),
    ]
