# Generated by Django 4.1.7 on 2023-04-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0014_capsule_status_capsule_status_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("US", "Unstaged"),
                            ("S", "Staged"),
                            ("P", "Processed"),
                        ],
                        default="US",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summaries",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Summary",
                "verbose_name_plural": "Article Summaries",
                "ordering": ("-id",),
            },
        ),
    ]
