# Generated by Django 4.1.7 on 2023-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0015_articlesummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesummary",
            name="text",
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
