# Generated by Django 4.1.7 on 2023-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0016_articlesummary_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesummary",
            name="status",
        ),
        migrations.AddField(
            model_name="articlesummary",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
