# Generated by Django 4.1.7 on 2023-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0017_remove_articlesummary_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
